using Microsoft.CodeAnalysis;
using static System.Net.Mime.MediaTypeNames;
using System.Xml.Linq;

namespace SourceGenerator
{
    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {

        public void Execute(GeneratorExecutionContext context)
        {

            var files = System.IO.Directory.GetFiles("nodes");
         

            for (int i = 0; i < files.Length; i++)
            {
                var path = files[i].Replace("\\", "\\");
                var name = files[i].Replace('\\', '-');
                name = name.Substring(6);
                name = name.Remove(name.IndexOf('.'));
                string source = $@"// <auto-generated/>
                
using System;

namespace  ClassLibraryPart_1
{{
    
    public partial class Vault
    {{
        static partial void Load{i}(Vault v) 
        {{
            
            Console.WriteLine($""Geytor sa: 32sdad '''"");
            var text = System.IO.File.ReadAllText(""{path}"");
            //var files = System.IO.Directory.GetFiles(""nodes"");
           // System.Console.WriteLine(files.Length);
            v.nodes.Add(new Node(""{name}"",text));
            //Console.WriteLine($""Geytor sa: 32sdad '''"");
        }}
    }}
}}
";
                context.AddSource($"{i}.g.cs", source);
            }

        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}